inherit_from: .rubocop_todo.yml
require: 
    - rubocop-rails
    - rubocop-faker
    - rubocop-rspec
AllCops:
    Exclude:
        - 'config/environments/development.rb'
        - 'db/schema.rb'
        - 'app/controllers/graphql_controller.rb'
        - 'app/services/generate_classic_map.rb'
        - 'app/graphql/loaders/association_loader.rb'
        - 'bin/bundle'
    NewCops: enable