inherit_from: .rubocop_todo.yml
require: 
    - rubocop-rails
    - rubocop-faker
    - rubocop-rspec
AllCops:
    Exclude:
        - 'config/environments/development.rb'
        - 'db/schema.rb'
    NewCops: enable